### ISSUE TITLE
Should the serve command save pages by default?

### ISSUE THREAD

**Issue by emmadesilva** [hydephp/develop#1994] opened 2024-11-05 13:36 UTC
Consider if we should change the serve command to not save pages by default (it's unexpected)

**Comment by caendesilva** [comment] 2024-11-05 13:37
Based on the code and documentation provided, I'll analyze whether the realtime compiler should save previewed pages by default.

Currently, the default behavior is to save preview pages (`save_preview = true`), as seen in:


```418:426:config/hyde.php
    'server' => [
        // The default port the preview is served on
        'port' => env('SERVER_PORT', 8080),

        // The default host the preview is served on
        'host' => env('SERVER_HOST', 'localhost'),

        // Should preview pages be saved to the output directory?
        'save_preview' => true,
```


However, there are several factors to consider:

1. **Purpose of Preview Server**: The realtime compiler is meant for local development and previewing changes, as noted in:


```9:10:docs/extensions/realtime-compiler.md
The Hyde Realtime Compiler is included with Hyde installations and is what powers the `php hyde serve` command,
allowing you to preview your static site on a local development server without having to rebuild the site.
```


2. **Development Focus**: Hyde emphasizes developer experience and simplicity, as shown in:


```35:37:CONTRIBUTING.md
- **Developer experience first:** Creating sites with Hyde and contributing to the framework should be a joy.
- **Zero config setup:** You should be able to just install Hyde and start building your project right away. Hyde should follow convention over configuration and come preconfigured with sensible defaults.
- **Customizable when you need it:** While configuration should not be a requirement, the option should always be there. As such, we should provide easy ways for customization to those who need it.
```


3. **Storage Implications**: Saving previews creates additional files that aren't necessarily needed for development purposes.

4. **Change History**: A change was made to add this configuration option, as noted in:


```241:242:CHANGELOG.md
### Added
- Added a RealtimeCompiler config option to disable rendered pages being stored to disk in https://github.com/hydephp/develop/pull/1334
```


Recommendation:
The default should be changed to `false` because:

1. During development/preview, saving files is not typically expected or necessary
2. It creates unnecessary file operations and storage usage
3. The primary purpose of `php hyde serve` is for previewing changes, not generating files
4. If users need to save the files, they can explicitly enable this via configuration
5. This aligns better with the principle of least surprise - most developers would expect a preview server to just show changes without writing files

The current default of `true` seems to go against the expected behavior of a development preview server. The setting should remain configurable, but defaulting to `false` would be more intuitive and aligned with typical development workflows.

**Comment by caendesilva** [comment] 2024-11-05 17:48
Fixed by https://github.com/hydephp/develop/pull/1995

**Closed as completed by caendesilva** 2024-11-05 17:48 UTC
